# Generated by Django 4.1.7 on 2023-03-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('owner_id', models.IntegerField(verbose_name='Владелец')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Имя владельца')),
                ('description', models.TextField(max_length=1000, verbose_name='Описание')),
                ('total_score', models.IntegerField(verbose_name='Макс.результат')),
                ('total_tasks', models.IntegerField(verbose_name='Всего заданий')),
                ('unchangeable', models.BooleanField(default=False)),
                ('include_weekly_report', models.BooleanField(default=False)),
                ('content_type', models.IntegerField(default=1, help_text='1 - Course; 2 - Quiz; 3 - Literature')),
                ('is_netology', models.BooleanField(default=False)),
                ('demo', models.BooleanField(default=False)),
                ('custom_author_names', models.CharField(max_length=255, verbose_name='Псевдонимы')),
                ('custom_contents_link', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('duration', models.IntegerField(help_text='Duration in sec.')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-id'],
            },
        ),
    ]
