# Generated by Django 4.1.7 on 2023-03-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='custom_contents_link',
            field=models.CharField(max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
